language: r
sudo: required
cache: packages

r_packages:
  - rmarkdown
  - Matching
  - cem
  - dplyr
  - magrittr

install:
  - Rscript -e "if (!require('ggplot2')) install.packages('ggplot2')"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "if (!require('rmarkdown')) install.packages('rmarkdown')"
  - Rscript -e "if (!require('Matching')) install.packages('Matching')"
  - Rscript -e "if (!require('cem')) install.packages('cem')"
  - Rscript -e "if (!require('dplyr')) install.packages('dplyr')"
  - Rscript -e "if (!require('magrittr')) install.packages('magrittr')"
  - Rscript -e "devtools::install_github('ivyleavedtoadflax/bookdown')"

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh
